### ISSUE TITLE
关于盖板螺丝

### ISSUE THREAD

**Issue by laognf95** [whowechina/mai_pico#1]
M2*5mm的自攻螺丝。。 只能堪堪露出尖头，锁不上盖板。。

我这边在嘉立创三维猴打印的按键，用M2*8mm的螺丝可以稳定锁上

**Comment by whowechina** [comment]
Those should be regular machine screws, not self-tapping screws.
要用普通螺丝，不要用自攻。打印材料很软，普通螺丝就能轻松“刻”出螺纹。
