### ISSUE TITLE
About the self-test interaction of the light control panel

### ISSUE THREAD

**Issue by CY202032** [whowechina/mai_pico#10]
Hope to repair this function, 15070-04, although it can be used at present, but always feel uncomfortable, obsessive-compulsive disorder patients said very uncomfortable. Ha ha ha

**Comment by whowechina** [comment]
Any details of the issue?

**Comment by CY202032** [comment]
Sorry, I don't know what the details are, just I don't understand, I tried to port the code, but it failed.

**Comment by whowechina** [comment]
What is "Light Control Panel" and what is "self-test interaction"?
I don't need codes, I just don't understand the problem.

**Comment by CY202032** [comment]
The problem is that when the status of the device is reported when the game starts, the led says bad, not good.

**Comment by whowechina** [comment]
Ah ok, I'll check that.

**Comment by whowechina** [comment]
I can't reproduce it. I tested with Festival JP version, the first 4 lines (Touch and LED for 1P/2P) all GOOD. I don't have other versions to test.

**Comment by CY202032** [comment]
No, no, no.You can put the mai2.ini Turn off the test for DummyLED.Let this item be 0, not 1.

[AM]
DummyLED=0

**Comment by CY202032** [comment]
LED handler: Comio.BD15070_4.BoardCtrl15070_4._execThread()
Print LED control data: Comio.Packet.dump()
Serial packet codec Comio.JvsSyncProtect
With DummyLED enabled, Comio.BoardCtrlBase.SendForceCommand still sends light data

The attachment is the data of the packet capture, which is for reference only, I hope it will help the logic

Thank you for your contribution to this project

[MaiLED-Data.txt](https://github.com/whowechina/mai_pico/files/14544316/MaiLED-Data.txt)

**Comment by whowechina** [comment]
> No, no, no.You can put the mai2.ini Turn off the test for DummyLED.Let this item be 0, not 1.
> 
> [AM] DummyLED=0

Got it.
