### ISSUE TITLE
ITO glass and full size maimai questions

### ISSUE THREAD

**Issue by OliverLSanz** [whowechina/mai_pico#11]
Hello Wowechina. First of all thank you for this and your other projects, all look amazing!

I have never used ITO glass. I have a question about it. If you touch the narrow strips that connect each touch area to the sensors, won't it make the sensor trigger? For example, if I touch here, won't the "X" marked areas trigger? Why?
![Captura](https://github.com/whowechina/mai_pico/assets/15345234/a7c88c81-df25-49ef-9a84-4ae48d9c30b5)

Also, I'm thinking about modifying the design to build a full size controller. Can you anticipate any major drawbacks or difficulties from doing this? (apart from cost of the materials, of course)

**Comment by whowechina** [comment]
It's all about SNR (signal to noise ratio), in this case, signal is the capacity change when a finger approaches the electrode (so the area of the electrode matters, in a linear way). Traces is like nothing compared with main touch area.

Firmware and design perfectly work for fullsize. In fact, SNR on fullsize should be better.
Making a full size ITO is just not worth, way too expensive, even if you make a 5 pcs batch.

**Comment by OliverLSanz** [comment]
I understand, thank you!

Could a IR Touch Frame replace the ITO Glass? I'm pondering the pros and cons and maybe you have any insight that will make me see that an IR Touch Frame is not a good idea.

**Comment by whowechina** [comment]
Then you have to change the code by youself. I don't have experiences with IR frame. Sadly I have never played a fullsize maimai too.

**Comment by OliverLSanz** [comment]
I know about the code, just wondering if yoy had any insights to share about IR Frame. Thank you again 😄
