### ISSUE TITLE
更新后固件刷上触摸只识别A1区

### ISSUE THREAD

**Issue by yakumoringo** [whowechina/mai_pico#12]

**Comment by whowechina** [comment]
Execute ‘factory’ command to reset to factory default settings. This is because a new touch mapping introduced in new firmware. Sorry about the inconvenience.在 2024年4月8日，11:58，5huxiaoyang6 ***@***.***> 写道：﻿

**Comment by whowechina** [comment]
Made some change. When upgrading from an old version which makes the touch map corrupted, it automatically resets the touch map to default.
