### ISSUE TITLE
Questions about the new AIC module in this project..

### ISSUE THREAD

**Issue by CY202032** [whowechina/mai_pico#13]
The new module is available, but at the beginning of the game, the network will be disconnected when repeatedly swiping the AIME card. I changed to other card readers and no similar problems occurred. After entering the test mode, I found that AIME did It works fine, but I don't know what went wrong.

新的模块是可用的，但是在游戏开始时，反复刷AIME卡的时候会出现断网的情况，我换了其他的读卡器，并没哟出现类似问题，进入test模式后发现AIME并没有掉，功能还是正常的，不清楚到底哪里出了问题。

**Comment by whowechina** [comment]
No idea why this happens. Have you tried with a standalone AIC Pico?
I noticed a short-lived "aime not available at this time" message before, and didn't figure out why. As it's not a big problem, I didn't dig into it.

**Comment by whowechina** [comment]
I think I've found a fix for the issue, will update shortly.

**Comment by whowechina** [comment]
Fixed.
