### ISSUE TITLE
A new bug in the AIC module

### ISSUE THREAD

**Issue by CY202032** [whowechina/mai_pico#14]
When swiping the card, you can press the 7 key to view the card number. When you quickly slide the AIME card or compatible card over the card reader, you will get the card number 0000-0000-0000-0000-0000 instead of your card number.

在刷卡的时候你可以按7键查看卡号，当你快速的将AIME卡或兼容卡从读卡器上滑过，你会得到的卡号0000-0000-0000-0000-0000而不是你的卡号。

**Comment by whowechina** [comment]
What if you swipe slowly? Process of reading aime card is slow.

**Comment by CY202032** [comment]
If I swipe slowly, it will be the correct card number, which is a small issue. Leaving it aside for now, there is another issue with the RGB standby light. If you are checking the card number and the idle light is on, or at other times, the idle light is on, it looks great. Then you return to the main page to swipe the card, but you don't clear the light effect and then turn on the corresponding light. Instead, you directly turn on the corresponding light.

**Comment by whowechina** [comment]
You mean the idle light effect is intruding the gaming light?

**Comment by whowechina** [comment]
Nothing I can do to accelerate the card reading.
