### ISSUE TITLE
Bro, can you separate the touch part and use DB9, RS232 for direct communication?

### ISSUE THREAD

**Issue by CY202032** [whowechina/mai_pico#16]
I just want to use the native protocol to connect directly to the COM interface.

**Comment by whowechina** [comment]
No idea what it means.
Mai Pico uses native protocol to talk to the arcade game thru a COM port.

**Comment by CY202032** [comment]
Actually, it's nothing, I just remembered it suddenly, promicro, esp32 and other development boards have this version, I suddenly remembered that 2040 doesn't have it, so I asked

**Comment by whowechina** [comment]
rp2040 has UARTs, but at 3.3V level, not RS232 level.
For maimai, there's no difference between USB CDC COM port and an ISA-RS232 COM port.

**Comment by CY202032** [comment]
OK,Close.
