### ISSUE TITLE
关于外壳

### ISSUE THREAD

**Issue by IlIIllllIlIIlll** [whowechina/mai_pico#17]
你好！我画好了一个外壳，我该如何贡献这个项目，我是新手，不太会用github
![Image_1724742278771](https://github.com/user-attachments/assets/dc0b9ca5-8c7d-4694-a65d-17fae48be344)

**Comment by whowechina** [comment]
感谢。
如果你自己有 github 账号和仓库，可以在自己的 github 页面发布（记得要同时发布源文件，可供他人二次编辑和加工的，并建议使用任何非商用类的协议，比如像我这样的 CC-NC），然后给我几张你成品的照片，我放到我的介绍里，并链接到你的仓库页面。

如果你不打算自行发布 github 仓库，把文件发给我，我可以放到我这边页面里面，我会写上原作者。

**Comment by IlIIllllIlIIlll** [comment]
想问一下，我如何怎么把文件发给你？是以邮箱的方式发送吗？

**Comment by whowechina** [comment]
可以试试在这里直接加附件。

**Comment by IlIIllllIlIIlll** [comment]
我在这里没法上传大文件

**Comment by whowechina** [comment]
最好你自己开个仓库分享外壳制作过程，包括选材，工艺，确保都是大家能容易订购到的。
我会把你的作品和仓库链接加到 Builds Gallery （制作集锦）里面。 你可以看看现在已经有几位爱好者的作品和链接了，其中 imfrea 也做了一个外壳。

**Comment by IlIIllllIlIIlll** [comment]
[mai pico外壳.zip](https://github.com/user-attachments/files/16762639/mai.pico.zip)

**Comment by whowechina** [comment]
看上去 STL 的都是需要打印的，正面背面材料应该是亚克力吧，多厚的？

**Comment by whowechina** [comment]
另外你给几个好看点的成品照片，以及你希望留下的你的名字（网名，昵称都可以）。

**Comment by IlIIllllIlIIlll** [comment]
> 看上去 STL 的都是需要打印的，正面背面材料应该是亚克力吧，多厚的？

正面和背面的材料是pp板材，边框可以亚克力定制也可以3D打印，支柱是3D打印，稍后晚点我写个装配过程文档。

**Comment by IlIIllllIlIIlll** [comment]
> 另外你给几个好看点的成品照片，以及你希望留下的你的名字（网名，昵称都可以）。

![IMG_20240827_220005.jpg](https://github.com/user-attachments/assets/2a791313-12f4-494f-9107-216fa36c095f)

![IMG_20240827_220020.jpg](https://github.com/user-attachments/assets/a64efbd0-ebec-4388-94a5-9439809a244e)

![IMG_20240827_220043.jpg](https://github.com/user-attachments/assets/4ac6d09b-b90d-454d-ac6d-adeef6edefa4)

**Comment by IlIIllllIlIIlll** [comment]
昵称就我现在github名

**Comment by IlIIllllIlIIlll** [comment]
> 另外你给几个好看点的成品照片，以及你希望留下的你的名字（网名，昵称都可以）。

![IMG_20240827_220005.jpg](https://github.com/user-attachments/assets/1549bdc2-726d-41fb-862d-376c9551f43f)

![IMG_20240827_230820.jpg](https://github.com/user-attachments/assets/f503a753-d589-4f3d-adb6-cbab92d6e687)

![IMG_20240827_220043.jpg](https://github.com/user-attachments/assets/f0b46f06-491c-4be6-90bf-b24992fb2edc)

**Comment by whowechina** [comment]
> > 看上去 STL 的都是需要打印的，正面背面材料应该是亚克力吧，多厚的？
> 
> 正面和背面的材料是pp板材，边框可以亚克力定制也可以3D打印，支柱是3D打印，稍后晚点我写个装配过程文档。

主要是材料选择（购买的时候需要提供的文件，参数等等），还包括螺丝的参数等等，大家可以根据你提供的参数自行找到供应商。

等你给我后，我更新上去。

**Comment by whowechina** [comment]
[7cb63b9](https://github.com/whowechina/mai_pico/commit/7cb63b93b9c24e5c1854f27253f25c45fcd50ca1)
