### ISSUE TITLE
Question about Pop'n Pico - Screws/Spacers

### ISSUE THREAD

**Issue by AbsentmindedGCN** [whowechina/mai_pico#18]
Hi there, sorry this issue is being uploaded in the wrong spot.
Could you please provide more information about the screws/spacer solution for the Pop'n Pico?
https://github.com/whowechina/popn_pico

I cannot find any 3.4mm/3.5mm M3 spacers. Do you have any suppliers that create them and the M3 screws?
Any help/advice would be extremely appreciated. Thanks a bunch!

![screw_solution (1)](https://github.com/user-attachments/assets/99734994-95a2-460d-b748-d7c2daee8ede)

**Comment by whowechina** [comment]
Google "hexagonal brass standoff". You may get a 4mm one and use a grinder to trim to 3.4mm, you may need to trim the screws too. Sorry about the inconvenience.
Popn Pico is my first attempt in my Pico Series, by the time I was not so experience, so housing design choices was not the best.

**Comment by AbsentmindedGCN** [comment]
Thank you very much! This is my first project I've tried to 3D print and I'm really excited.
I have another question if you have a moment. When trying to print these with JLC, they are saying that the bottom wall thickness is too thin, causing high risks of cracks and deformation. They recommend increasing the size to at least 0.8mm, but 1.5mm would be ideal.

![thin](https://github.com/user-attachments/assets/4722db7b-63bf-4056-90ed-ee3adb9f3fa8)

Would it be possible to increase these to 0.8mm and update the STL? I am very sorry to ask but I do not have access to AutoCAD.

**Comment by whowechina** [comment]
![image](https://github.com/user-attachments/assets/f7c1cf48-bb7d-41b4-b04e-a4d4e9cc6a28)

Those places are supposed to be that thin. I printed on my old cheap printer, and it went well. So as long as the print bed is properly leveled it will be fine.
3D printing is not durable as commercial products, it's more for prototyping or for hobby projects like this.

**Comment by AbsentmindedGCN** [comment]
This is a hobby project, I am excited to play Pop'n. :)
I will go ahead with the 3D print if you think there is no issue with it being 0.6mm. I do not have a 3D printer so I am ordering the 3D printed parts from JLC.
Thank you very much for creating this!

**Comment by AbsentmindedGCN** [comment]
Do you have the original source file for the STL that I can edit? I would like to increase the size of the bottom by 1mm if possible. I tried to make an adjustment but editing the STL file is difficult and it will not work for JLC to print. :(
[pico_popn_case_updated.zip](https://github.com/user-attachments/files/16885066/pico_popn_case_updated.zip)
