### ISSUE TITLE
3D模型部分区域壁厚太薄

### ISSUE THREAD

**Issue by WYH2004-MC** [whowechina/mai_pico#2]
部分壁厚太薄了，打印精度不够可能会有问题
![mmexport1703830807338.jpg](https://github.com/whowechina/mai_pico/assets/32890512/87a4faa1-1fa5-460f-8830-7e964ce6ed2d)

![mmexport9c56ab15281de06b6cf32343c07991c8_1703831602550.png](https://github.com/whowechina/mai_pico/assets/32890512/f31b47ec-9791-45c1-a4ff-1cf6760fd2f4)

**Comment by whowechina** [comment]
I'm not going to change for following reasons.
* They work well on Bambu printers.
* I don't have other printer system to verify.
* Source CAD files are open, one can finetune based on his/her(hopefully) own results.
