### ISSUE TITLE
Pop'n Pico - No Response/USB Issue

### ISSUE THREAD

**Issue by AbsentmindedGCN** [whowechina/mai_pico#21]
Hi whowechina!

I am sorry for bothering you again but I had another question regarding the Pop'n Pico. I was able to get the parts, PCBs, and printed case. I have been trying to solder everything, but I have been running into an issue.

When I plug the board into my computer, either by USB-C or Micro-USB, the board won't respond. Any other USB devices will stop working, like my USB mouse, or my external HDD. I have tried holding the BOOTSEL button down and that makes no difference. I have tried soldering one board then putting the firmware on, and another board where I put the firmware on before soldering. The issue occurs on both boards, across multiple PCs.

I am trying to determine the source of the issue but I'm honestly very lost and not sure what the issue is. Photos of the 2 boards I soldered are below:

Board 1: (This was messy with flux, sorry!!)
![20240928_201839](https://github.com/user-attachments/assets/a928d4e5-a222-460f-b5c6-3b58091eaa75)
![20240928_201825](https://github.com/user-attachments/assets/ecd1cf28-8443-4aca-a0ac-4ce4cc426876)

Board 2 (no RGB):
![20240928_201922](https://github.com/user-attachments/assets/8a84010b-28c4-4cec-a923-a30043b8d771)
![20240928_201944](https://github.com/user-attachments/assets/d7f01d4f-b547-43d7-a64d-5d4d028a0b93)

I have a couple of questions if you have a moment:
Do you see any noticeable problems on the board that could be causing this issue?
Are there any pins on the Pico I'm not supposed to solder?
What is the most likely part/section that could be causing this? (eg. resistors?)

Any help/advice would be really appreciated. I'm sorry again for being bothersome.
Thank you again for making this project and sharing it with others, it has been really fun to learn SMD soldering!

**Comment by whowechina** [comment]
You may move the issue to Pop'n repo (I just enabled it there).
USB not responding is because there's some short-circuit, very likely at the Type-C connector soldering.
And 4020 LEDs on your first board are facing wrong direction.

**Comment by whowechina** [comment]
![{1B30D8BB-C942-4BE0-98B5-99F0C951CC13}](https://github.com/user-attachments/assets/6cb4198e-95b1-4f6a-aa96-01d4133ead44)
This looks not good.

**Comment by whowechina** [comment]
![{592F04E8-CD05-4896-B958-834277BBAD9D}](https://github.com/user-attachments/assets/38392469-7574-407d-b881-47934e04c70a)
This also not good.

The 4 bigger pins at both sides are VCC and GND, if they touch each other, boom!

**Comment by AbsentmindedGCN** [comment]
Thank you so so much for checking. I will resolder the USB-C. I will also move this over to the Pop'n Pico project if I have any other issues. I'm very sorry for bothering and really appreciate your help.

Will this USB-C still cause an issue even when connecting with microUSB? I was surprised the issue was still happening even without USB-C. 

Thank you again for your help!!

**Comment by AbsentmindedGCN** [comment]
![20240929_184956](https://github.com/user-attachments/assets/e9763a47-682d-41da-a86e-b611c11fa1d7)
Is this any better or is the USB-C still an issue

This is not responding when connected to my PC :(

**Comment by whowechina** [comment]
> This is not responding when connected to my PC :(

This looks better. This time it didn't stop other devices right?

Very likely these three are not soldered to the pad (air bubbles in them). You only need to repair the left two pads.
![{B20C0EAD-61F7-4257-AD7E-78DC5443C924}](https://github.com/user-attachments/assets/77e6b075-f79b-470d-8cd2-4924b6d9430d)

**Comment by whowechina** [comment]
By the way, using a cotton swab dipped in PCB cleaner can nicely clean the PCB board.

**Comment by AbsentmindedGCN** [comment]
It's still stopping other devices and is not working. :(
I will clean the PCB

Do you have any tips on soldering the 3 holes? I put the iron into the solder to get it to the bottom of the pico after soldering it to the other side of the board

Would the resistors be a problem that could cause this? I'm trying to think why the same issue would happen with USB-C and Micro USB

**Comment by whowechina** [comment]
In some other repos (maybe chu_pico or geki_pico), I left some notice for these pins.
Resistors won't cause this problem. Wrong orientation of LEDs or short-circuit of VCC and GND could lead to this problem.

**Comment by AbsentmindedGCN** [comment]
I checked the orientation of the LEDs (they lit up while soldering) and made sure those were on the right side. The RGB lights were difficult and I am not sure if I am able to include them. Are they necessary for the board to work?

I will check for any short circuits on the Pico

**Comment by AbsentmindedGCN** [comment]
Thank you for your help!! I cleaned up the boards and jammed my soldering iron through the 3 holes to make sure they got soldered through. That fixed one of the boards!

I'm not getting any LEDs working, and I'm going to try to fix/make another board, but I'm really excited this one works!!

![20240930_234140](https://github.com/user-attachments/assets/b24223e0-7454-4e7c-b7b7-ec832bcf3cdb)

Thank you again for making this project and thank you for all your help! This has been really fun to do!!
Do you accept donations anywhere?

**Comment by whowechina** [comment]
Only RGB LED could lead to short-circuit if orientation is wrong.
Congratulations on your first DIY con, there're other pico cons I made. :)
The firmware allows light brightness and fading controll.

No, I don't accept donations.
Just encourage more of your friends to build my pico series cons.
