### ISSUE TITLE
button and touchscreen cannot work together in my mai pico. What could be the possible solution

### ISSUE THREAD

**Issue by Panda2397** [whowechina/mai_pico#22]
The 8 main button only have button 4 5 6 are workable with touchscreen worked. However, when I replug the USB, all 8 button can simulate keyboard output (it worked) but touchscreen didn't work.

**Comment by whowechina** [comment]
Sounds like it's not a mai pico hardware or firmware issue.
You can try IO4 mode.

**Comment by Panda2397** [comment]
Thanks for your answer. I have changed the LED from com21 to others and
finally the button worked. However the LED dont. What could be the possible
reason for that

在 2024年12月4日週三 下午3:11，whowechina ***@***.***> 寫道：
