### ISSUE TITLE
s?g?tools.ini config help!

### ISSUE THREAD

**Issue by Linkcore4423** [whowechina/mai_pico#3]
Can anyone tell me how to configure s.ini? I am trying to write UF2 firmware, and a device named "Mai Pico" also appears in Windows. How can I configure my ini file?

The current configuration is as follows:

[vfs]
amfs=amfs
appdata=appdata
option=option

[dns]
default=16.0.0.140

[io4]
enable=0

[button]
enable=0

[aime]
enable=1

[jvs]
enable=0

The current symptom is getting stuck in Aime Check.
![sps](https://github.com/whowechina/mai_pico/assets/26422953/c4693525-5648-440b-b86f-2fcd74b8f707)

**Comment by Becods** [comment]
This problem is not caused by mai_pico.

You should ask the right questions in the right place.

**Comment by whowechina** [comment]
Yeah, it's not ok to talk things like this here.
