### ISSUE TITLE
Questions about sourcing ITO glass

### ISSUE THREAD

**Issue by Leapward-Koex** [whowechina/mai_pico#4]
First of all, thanks for the writeup, its looks pretty straightforward and cool.

I have a question about sourcing the required glass. It seems relatively hard to find but I found this website [walthly](https://walthy.com/)  that say they can do it. 

My only issue is that I was quoted $1500USD for their min order of 5 pieces, this seems quite excessive.

Is this similar to what sourcing it through the mentioned [taobao](https://shop378788148.taobao.com/?spm=2013.1.1000126.2.305e16c4LFf1GW) store was?

**Comment by whowechina** [comment]
That sounds way way way too much. Should be less than 200usd.
