### ISSUE TITLE
[Bug Report] Stuck on aime check when using io4

### ISSUE THREAD

**Issue by Becods** [whowechina/mai_pico#5]
### Bug Description

Stuck on aime check when using io4
![U_6Y87EM G4~DZKG9JVCS{T](https://github.com/whowechina/mai_pico/assets/35525491/ff8dbc8e-408f-424f-a51c-913840de1e83)

### Steps to reproduce

1. Set segatools' io4 emulation to disable
```
[io4]
enable=0
```
2. Plug in the rp2040 with the burned-in firmware from the `Production`
3. Set hid to joy
4. Launching the game

### Other

I tried to use [lkick-io4](https://github.com/XxLittleCxX/lkick-io4) and it works everything perfectly

But I had to use multiple boards to replace what would have been done with a single board

**Comment by whowechina** [comment]
Sounds not an io4 problem. Use Windows Joystick tool from control panel to check if io4 hid is working properlly.
So far, mai pico has not integrated aime (aic pico).
There's a chance that one of the com port from mai pico happened to be the aime port the game was expecting, you need to sort it out.

**Comment by Becods** [comment]
![image](https://github.com/whowechina/mai_pico/assets/35525491/483552ec-799e-4400-a6e7-5fe42ca391b0)

I've tried to connect the card reader but the problem persists

The card reader is from [Arduino-Aime-Reader](https://github.com/Sucareto/Arduino-Aime-Reader), I tested it separately and it works fine

**Comment by whowechina** [comment]
Thank you for the report. The hid looks fine.
I'm afraid I can't do anything, unless it's a very specific hid or protocol issue. It's not ok to talk or help with arcade data related things here.

Maybe go with nkro, it has same latency and polling rate.

**Comment by whowechina** [comment]
This is actually a valid issue, so I reopened it. Why the IO4 has impact to AIME server check is still a mystery to me.

**Comment by whowechina** [comment]
Turned out it has something to do with io4 hid output. Now it's fixed. Thank you. @Becods
