### ISSUE TITLE
ITO玻璃可否倒角？

### ISSUE THREAD

**Issue by imfrea** [whowechina/mai_pico#6]
您好，ITO玻璃的四角能否做成类似于官方原装触屏那种样式？
正方形的四角锋利且占据一定空间，如果能剪裁掉或将更加完美（不知道这是否会增加成本）
![IMG_1324](https://github.com/whowechina/mai_pico/assets/28303037/61ba45b2-f577-4cb5-b4ea-9d6e734fe9b1)

**Comment by whowechina** [comment]
爱好者只买几块的情况下，厂商可能不大愿意麻烦，除非多加点钱。技术上说，只要不切到走线怎么弄都可以。
用醋酸胶带包裹边缘也是一个不错的选项，我的部分截图里可以看到。
