### ISSUE TITLE
灯光不支持 Fading，按键不支持投币

### ISSUE THREAD

**Issue by CY202032** [whowechina/mai_pico#7]
mai2led已经更新，您的项目可否更新一下呢？
按键部分无法投币，
灯光部分还有一些不足，呼吸效果，渐变效果都没有。
如果补全这个工程真的就太棒了

**Comment by whowechina** [comment]
呼吸和渐变，我没见过实物或者资料，所以不知道怎么实现。
如果有这些效果的视频（最好不是在玩的时候，而是在 demo 的时候），那就很容易做了。

**Comment by CY202032** [comment]
这个呼吸渐变是在无人游玩的时候，播放demogame时候的灯光效果，有联系方式么？探讨一番可否？
mai2led是已经实现这个功能了

**Comment by whowechina** [comment]
我在 Discord C&S 活动，过年回老家了，回杭后加灯光 Fade In/Out。
另外，帮忙把 issue 标题写具体一些，读起来友好。

**Comment by whowechina** [comment]
我记得投币按钮也做进去了，只是没有改 pcb，这个板子画的很随意，草稿可用后就没有优化，从 pico 直接引线即可。

**Comment by whowechina** [comment]
![Uploading Picsart_24-02-12_21-32-17-960.jpg…]()

**Comment by whowechina** [comment]
![Picsart_24-02-12_21-32-17-960](https://github.com/whowechina/mai_pico/assets/11623830/cf639717-335c-4987-a29b-bce4c4a1cd14)

**Comment by CY202032** [comment]
mai2的投币是滑块，并不是按钮，实现起来比较麻烦。。。

namespace component {
    namespace io4_usb {
        output_t output_data;
        output_keyboard_t output_keyboard_data;
        static bool coin_triggered = false;
        TaskHandle_t h_add_coin;
        [[noreturn]] static void add_coin_task(void *arg) {
            gpio_init(22);
            gpio_set_dir(22, GPIO_IN);
            gpio_pull_up(22);
            while (true) {

                    bool button_state = !gpio_get(22);
                    if (!coin_triggered && button_state) {
                        output_data.coin[0].count++;
                        printf("coin_task: inserted coin\n");
                        coin_triggered = true;
                    } else if (coin_triggered && !button_state) {
                        coin_triggered = false;
                    }
                vTaskDelay(200 / configTICK_RATE_HZ);

            }
        }
        void usb_init() {
            gpio_init(22);
            gpio_set_dir(22, GPIO_OUT);
            gpio_put(22, 0);
            xTaskCreate(add_coin_task, "test_coin", 4096, nullptr, 5, &h_add_coin);

        }

**Comment by whowechina** [comment]
好的，这个简单。

**Comment by whowechina** [comment]
> mai2的投币是滑块，并不是按钮，实现起来比较麻烦。。。
>```
>     output_data.coin[0].count++;
>```
它的投币怎么“消耗”的，也就是 `count--`  的逻辑在哪里？
另外你引用的 `io4 output_data` 的结构体帮忙在这里贴一下。

**Comment by CY202032** [comment]
不好意思啊，我这个东西也是个半成品逻辑很混乱，理论上是chutes[2]，我也不是很理解这个东西。。关于这个东西我也是很费解，所以代码都是乱七八糟的，本身也不是我写的。。读卡器功能你也可以加入到工程中就非常完善了。这个userid是我WX号，方便交流可以加一下，本身我对C不是很了解。
#include "stdinclude.h"

namespace component {
    namespace io4_usb {
        enum class coin_condition_t: uint8_t {
            normal = 0x0,
            jam=0x1,
            disconnect=0x2,
            busy=0x3
        };

        struct coin_data_t {
            coin_condition_t condition;
            uint8_t count;
        } __attribute((packed));

        struct output_t {
            int16_t analog[8];
            int16_t rotary[4];
            // 10bit be number
            coin_data_t coin[2];
            uint16_t switches[2];
            uint8_t system_status;
            uint8_t usb_status;
            uint8_t _unused[29];
        } __attribute((packed)) ;

        enum cmd_t : uint8_t {
            SET_COMM_TIMEOUT = 0x01,
            SET_SAMPLING_COUNT = 0x02,
            CLEAR_BOARD_STATUS = 0x03,
            SET_GENERAL_OUTPUT = 0x04,
            SET_PWM_OUTPUT = 0x05,
            UPDATE_FIRMWARE = 0x85,
        };

        struct input_t {
            uint8_t report_id;
            cmd_t cmd;
            uint8_t payload[62];
        } __attribute((packed));

        // keyboard data
        struct output_keyboard_t {
            uint8_t modifier;
            uint8_t reserved;
            uint8_t keycodes[6];
        } __attribute((packed));
        
        void usb_init();

        [[noreturn]] void tud(void *pVoid);

        void process_data(const input_t *data);
    }
}


#include "stdinclude.h"

#include "config.h"
#include "Effects/Marquee.hpp"
#include "hardware/adc.h"
#include "stdinclude.h"

#include "hardware/adc.h"
#include "pico/bootrom.h"
#include "pico/error.h"
#include "../analogRead/analog_read.h"
#include "scancode.h"

namespace component {
    namespace io4_usb {
        output_t output_data;
        output_keyboard_t output_keyboard_data;
        static bool coin_triggered = false;
        TaskHandle_t h_add_coin;
        [[noreturn]] static void add_coin_task(void *arg) {
            gpio_init(22);
            gpio_set_dir(22, GPIO_IN);
            gpio_pull_up(22);
            while (true) {

                    bool button_state = !gpio_get(22);
                    if (!coin_triggered && button_state) {
                        output_data.coin[0].count++;
                        printf("coin_task: inserted coin\n");
                        coin_triggered = true;
                    } else if (coin_triggered && !button_state) {
                        coin_triggered = false;
                    }
                vTaskDelay(200 / configTICK_RATE_HZ);

            }
        }
        void usb_init() {
            gpio_init(22);
            gpio_set_dir(22, GPIO_OUT);
            gpio_put(22, 0);

            xTaskCreate(tud, "tud", 2048, NULL, 10, NULL);
            xTaskCreate(add_coin_task, "test_coin", 4096, nullptr, 5, &h_add_coin);

        }

        [[noreturn]] void tud(void *pVoid) {
            using namespace component::config;
            uint8_t last_mode = 0;

            auto aime_led = aime_reader::getController();
            std::vector<PicoLed::Color> rainbow_palette;
            rainbow_palette.push_back(PicoLed::RGB(255, 0, 0));
            rainbow_palette.push_back(PicoLed::RGB(255, 255, 0));
            rainbow_palette.push_back(PicoLed::RGB(0, 255, 0));
            rainbow_palette.push_back(PicoLed::RGB(0, 255, 255));
            rainbow_palette.push_back(PicoLed::RGB(0, 0, 255));
            rainbow_palette.push_back(PicoLed::RGB(255, 0, 255));
            PicoLed::Marquee effect_marquee(aime_led, rainbow_palette, 3.0, -2.0, 1.0);

            tusb_init();
            while (true) {
                tud_task();

                uint8_t this_mode = get_mode();
                switch (this_mode) {
                case MODE::KEYBOARD:
                    if (last_mode != this_mode) {
                        aime_led.setBrightness(0x2f);
                        led_board::set_color(0xff, 0xff, 0xff);
                        led_board2::set_color(0xff, 0xff, 0xff);
                        using namespace component::mai2_hardware;
                        set_led(0xffffff);
                        set_led_brightness(0x4f);
                    }
                    if (effect_marquee.animate())
                        aime_led.show();

                    component::mai2_hardware::update_keyboard(&output_keyboard_data);

                    if (tud_hid_ready())
                        tud_hid_report(0x02, &output_keyboard_data, sizeof(output_keyboard_data));
                    break;
                case MODE::IO4:
                    if (last_mode != this_mode){
                        aime_led.setBrightness(0xff);
                        aime_reader::set_card_light(0, 0, 0);
                        led_board::init_color();
                        led_board2::init_color();
                        using namespace component::mai2_hardware;
                        set_led(0xffffff);
                        set_led_brightness(0xff);
                    }

                    component::mai2_hardware::update_hardware(&output_data);

                    if (tud_hid_ready())
                        tud_hid_report(0x01, &output_data, sizeof(output_data));
                    break;
                default:
                    break;
                }
                last_mode = this_mode;
                vTaskDelay(6 / portTICK_PERIOD_MS);
            }
        }

        void process_data(const input_t *data) {
            switch (data->cmd) {
                case io4_usb::SET_COMM_TIMEOUT:
                    //uart_puts(uart1,"IO4: Set Communicate Timeout\n");
                    output_data.system_status = 0x30;
                    break;
                case io4_usb::SET_SAMPLING_COUNT:
                    //uart_puts(uart1,"IO4: Set Sampling Count\n");
                    output_data.system_status = 0x30;
                    break;
                case io4_usb::CLEAR_BOARD_STATUS:
                    // uart_puts(uart1,"IO4: Clear Board Status\n");
                    output_data.coin[0].count = 0;
                    output_data.coin[0].condition = io4_usb::coin_condition_t::normal;
                    output_data.coin[1].count = 0;
                    output_data.coin[1].condition = io4_usb::coin_condition_t::normal;
                    output_data.system_status = 0x00;
                    break;
                case io4_usb::SET_GENERAL_OUTPUT: {
                    uint32_t ledData = data->payload[0] << 16 | data->payload[1] << 8 | data->payload[2];
                    component::mai2_hardware::set_led(ledData);
                    //uart_puts(uart1,"IO4: Set General Output\n");
                    break;
                }
                default:
                    break;
            }
        }

//--------------------------------------------------------------------+
// USB HID
//--------------------------------------------------------------------+

// Invoked when received GET_REPORT control request
// Application must fill buffer report's content and return its length.
// Return zero will cause the stack to STALL request
        extern "C" uint16_t
        tud_hid_get_report_cb(uint8_t itf, uint8_t report_id, hid_report_type_t report_type, uint8_t *buffer,
                              uint16_t reqlen) {
            return 0;
        }

// Invoked when received SET_REPORT control request or
// received data on OUT endpoint ( Report ID = 0, Type = 0 )
        extern "C" void
        tud_hid_set_report_cb(uint8_t itf, uint8_t report_id, hid_report_type_t report_type, uint8_t const *buffer,
                              uint16_t buf_size) {
            auto data = reinterpret_cast<const component::io4_usb::input_t *>(buffer);
            if (data->report_id== 0x10) {
                process_data(data);
            }
        }
    }
}

**Comment by whowechina** [comment]
谢谢！
不过不需要大块贴代码，这样会把讨论弄很乱，一般一两行就足够表达意思了。
我回头空了自己摸索一下，应该非常简单。
另外我倾向于简洁的公开讨论，如果能用英文更好。

**Comment by CY202032** [comment]
I'm really sorry, my English is very poor, so I can't read some sentences. Sorry again, thank you for your efforts. I like this project very much, and it's very stable so far.

**Comment by whowechina** [comment]
> I'm really sorry, my English is very poor, so I can't read some sentences. Sorry again, thank you for your efforts. I like this project very much, and it's very stable so far.

哈，没事。只是这个仓库面对很多不同语言的人，英语会方便别人而已，说不定别人还能帮忙。

**Comment by CY202032** [comment]
[Mai2LED.zip](https://github.com/whowechina/mai_pico/files/14296536/Mai2LED.zip)

This is the project file, which contains the light self-inspection part of 837-15070-04. I hope you can learn from it. It's a pity that I haven't had time to test the project you updated.

这是工程文件，里面包含了837-15070-04的灯光自检部分，希望能借鉴，您更新的工程我还没有时间测试，真是可惜呢。。

**Comment by CY202032** [comment]
After testing, it was found that the updated project lighting had serious issues, and the buttons did not respond. They began to input strings on their own. Unable to further test...

经过测试，更新的项目灯光出现了严重的问题，按键也无反应了，开始自行输入字符串。无法进一步测试。。。
