### ISSUE TITLE
IO板与ITO玻璃解耦合，接插件的选择，layout优化

### ISSUE THREAD

**Issue by imfrea** [whowechina/mai_pico#8]
#### 一、接插件的选择
个人认为针对本项目的实际情况，按钮的走线设计和体积，保留JST EH连接器没有太多意义，在此建议如下：
1. 在IO板上多增加一个集中式的8PIN SH1.25端子座，定义为BT1…BT8
以及相应的SH1.25 3P（RGB输出）
按钮板则可以统一焊接一根SH1.25单头端子线（如图）
![IMG_20240225_125556](https://github.com/whowechina/mai_pico/assets/28303037/29aac82f-90ae-47d9-b723-cf2ec78a5680)

2. 在按钮PCB的J2/J4任意一个焊盘与GND之间预留一个0R电阻位，短接时共地，可节约简化走线（如图）
![0r](https://github.com/whowechina/mai_pico/assets/28303037/02796705-85ec-415c-90df-3745fad71f7e)

#### 二、IO板与ITO玻璃解耦合
目前控制板与ITO玻璃一对一焊死，不利于后期搬运和维护
出于DIY条件有限的考虑，无法直接将普通FPC绑定到ITO玻璃上
1. 建议增加一片0.8mm厚的PCB将1.6mm斑马纸排线转为常见的1.0间距34P的FPC排线（双头或单头焊接），并布置相应的排线座

其他方案：或许可以将3颗MPR121分立器件单独置于一块PCB上，缩短触屏线路的距离，另一端则使用I2C连接到IO板（如果I2C不适合长距离传输，请您考虑增加一颗MCU将信号流处理并转换为串口通讯）

#### 三、layout优化
原型PCB的layout不是十分紧凑
1.建议新的PCB中取消MPR121模块的设计，仅保留MPR121分立设计（分立电路部分经过验证可用），且芯片的价格低于模块

2.其他：考虑采用RP2040 Zero模块？因为体积小巧io也足够（模块反面有元件，可在PCB中间开窗，沉板设计，模块的Type-C接口直接对外（大致示意如图）
![new-layout](https://github.com/whowechina/mai_pico/assets/28303037/c4848a8b-7f35-40a3-996f-d2f06a56e44c)

双面元器件以及4层设计？

希望您能考虑采用立创EDA绘制PCB，有助于节约打样成本
*****
以上均为个人的想法和意见，可能不是很成熟，恳请您认真考虑和是否要采纳。

抱歉，我的英语不好，我也不会使用PCB设计软件，请见谅。
我正计划“本土化”文档并补充更多的细节与提示。
如果可能，希望您能在关闭issue前，留下**Email**以便交流，谢谢！

**Comment by whowechina** [comment]
谢谢提想法。虽然项目里有很多值得改进的细节，但我暂时不打算更新 PCB。
它现在对爱好者来说“可用”、“够用”，个人 DIY，过程就是乐趣，不会太介意多焊接几个点；作为”商品“也许有很多不足，但因为我极力反对任何人用本项目来”盈利“，所以没计划做这些改进。

中文的指南（包括我其他项目的）都在撰写中，我后续会在本仓库更新，方便国内爱好者。

**Comment by whowechina** [comment]
中文版本指南发布后我会关闭这个 Issue。
任何制作过程中发现的问题可以开 Issue 咨询，但务必不要提及任何游戏拷贝相关的内容。
